title: "数学好きのためのHaskell入門"
summary: "数学好きのためのHaskell入門です。"
topics: ["haskell", "math"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - intro
  - install
  - calc
  - function
