title: "Haskellでの型レベルプログラミング"
summary: "Haskellでの型レベルプログラミングの解説書です。まだ執筆途中です。"
topics: ["haskell"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - preface
  - types-and-kinds
  - phantom-types-and-proxy
  - datatype-promotion
  - type-families
  - type-classes
  - gadts
  - examples
  - singletons
  - theorem-proving
  - constraint-kinds
  - ghc-typenats
